# Generated by Django 5.0.9 on 2024-12-05 02:29

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalSurveys',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('slug', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='uuid')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('update_at', models.DateTimeField(blank=True, null=True, verbose_name='Ultima actualizacion')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Eliminado')),
                ('name', models.CharField(max_length=2000, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripcion')),
                ('type', models.CharField(choices=[('complaint', 'Queja'), ('suggestion', 'Sugerencia'), ('congratulation', 'Felicitación')], verbose_name='Tipo')),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'En proceso'), ('CANCELED', 'Cancelada'), ('FINISHED', 'Finalizada')], default='IN_PROGRESS', verbose_name='Tipo')),
                ('phone', models.CharField(max_length=10, verbose_name='Telefono')),
                ('is_removed', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('update_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Encuenta',
                'verbose_name_plural': 'historical Encuestas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Surveys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='uuid')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(blank=True, null=True, verbose_name='Ultima actualizacion')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Eliminado')),
                ('name', models.CharField(max_length=2000, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripcion')),
                ('type', models.CharField(choices=[('complaint', 'Queja'), ('suggestion', 'Sugerencia'), ('congratulation', 'Felicitación')], verbose_name='Tipo')),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'En proceso'), ('CANCELED', 'Cancelada'), ('FINISHED', 'Finalizada')], default='IN_PROGRESS', verbose_name='Tipo')),
                ('phone', models.CharField(max_length=10, verbose_name='Telefono')),
                ('is_removed', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_surveys', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_surveys', to=settings.AUTH_USER_MODEL)),
                ('update_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_surveys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Encuenta',
                'verbose_name_plural': 'Encuestas',
            },
        ),
    ]
