# Generated by Django 5.0.9 on 2024-12-09 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsurveys',
            name='type',
            field=models.CharField(choices=[('COMPLAINT', 'Queja'), ('SUGGESTION', 'Sugerencia'), ('CONGRATULATION', 'Felicitación')], verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='surveys',
            name='type',
            field=models.CharField(choices=[('COMPLAINT', 'Queja'), ('SUGGESTION', 'Sugerencia'), ('CONGRATULATION', 'Felicitación')], verbose_name='Tipo'),
        ),
        migrations.CreateModel(
            name='SurveyComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('response', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='surveys.surveys')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
