# Generated by Django 5.0.9 on 2024-12-10 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_surveycomments_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveycomments',
            name='response',
        ),
        migrations.AddField(
            model_name='historicalsurveys',
            name='contact_email',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Email del contacto'),
        ),
        migrations.AddField(
            model_name='historicalsurveys',
            name='contact_name',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Nombre del contacto'),
        ),
        migrations.AddField(
            model_name='historicalsurveys',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Telefono del contacto'),
        ),
        migrations.AddField(
            model_name='historicalsurveys',
            name='content',
            field=models.JSONField(default={}, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='historicalsurveys',
            name='ranking',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ranking de sugerencia'),
        ),
        migrations.AddField(
            model_name='historicalsurveys',
            name='type_2',
            field=models.CharField(blank=True, choices=[('COMPLAINT', 'Queja'), ('SUGGESTION', 'Sugerencia'), ('CONGRATULATION', 'Felicitación')], null=True, verbose_name='Tipo 2'),
        ),
        migrations.AddField(
            model_name='historicalsurveys',
            name='type_3',
            field=models.CharField(blank=True, choices=[('COMPLAINT', 'Queja'), ('SUGGESTION', 'Sugerencia'), ('CONGRATULATION', 'Felicitación')], null=True, verbose_name='Tipo 3'),
        ),
        migrations.AddField(
            model_name='surveycomments',
            name='is_removed',
            field=models.BooleanField(default=False, verbose_name='Eliminado'),
        ),
        migrations.AddField(
            model_name='surveys',
            name='contact_email',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Email del contacto'),
        ),
        migrations.AddField(
            model_name='surveys',
            name='contact_name',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Nombre del contacto'),
        ),
        migrations.AddField(
            model_name='surveys',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Telefono del contacto'),
        ),
        migrations.AddField(
            model_name='surveys',
            name='content',
            field=models.JSONField(default={}, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='surveys',
            name='ranking',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ranking de sugerencia'),
        ),
        migrations.AddField(
            model_name='surveys',
            name='type_2',
            field=models.CharField(blank=True, choices=[('COMPLAINT', 'Queja'), ('SUGGESTION', 'Sugerencia'), ('CONGRATULATION', 'Felicitación')], null=True, verbose_name='Tipo 2'),
        ),
        migrations.AddField(
            model_name='surveys',
            name='type_3',
            field=models.CharField(blank=True, choices=[('COMPLAINT', 'Queja'), ('SUGGESTION', 'Sugerencia'), ('CONGRATULATION', 'Felicitación')], null=True, verbose_name='Tipo 3'),
        ),
    ]
