# Generated by Django 5.0.9 on 2024-12-10 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_remove_surveycomments_response_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsurveys',
            name='content',
        ),
        migrations.RemoveField(
            model_name='surveys',
            name='content',
        ),
        migrations.AlterField(
            model_name='historicalsurveys',
            name='type_2',
            field=models.CharField(blank=True, choices=[('BAD_SERVICE', 'Mal servicio'), ('PRODUCT_QUALITY', 'Calidad en el producto'), ('OTHER_REASONS', 'Otras Razones'), ('GOOD_SERVICE', 'Buen servicio')], null=True, verbose_name='Tipo 2'),
        ),
        migrations.AlterField(
            model_name='historicalsurveys',
            name='type_3',
            field=models.CharField(blank=True, choices=[('DELIVERY_MAN', 'Repartidor'), ('CALL_CENTER', 'Call center'), ('BOTH', 'Ambos')], null=True, verbose_name='Tipo 3'),
        ),
        migrations.AlterField(
            model_name='surveys',
            name='type_2',
            field=models.CharField(blank=True, choices=[('BAD_SERVICE', 'Mal servicio'), ('PRODUCT_QUALITY', 'Calidad en el producto'), ('OTHER_REASONS', 'Otras Razones'), ('GOOD_SERVICE', 'Buen servicio')], null=True, verbose_name='Tipo 2'),
        ),
        migrations.AlterField(
            model_name='surveys',
            name='type_3',
            field=models.CharField(blank=True, choices=[('DELIVERY_MAN', 'Repartidor'), ('CALL_CENTER', 'Call center'), ('BOTH', 'Ambos')], null=True, verbose_name='Tipo 3'),
        ),
    ]
