# Generated by Django 5.0.9 on 2024-12-11 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0005_remove_historicalsurveys_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsurveys',
            name='name',
        ),
        migrations.RemoveField(
            model_name='historicalsurveys',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='surveys',
            name='name',
        ),
        migrations.RemoveField(
            model_name='surveys',
            name='phone',
        ),
        migrations.AlterField(
            model_name='historicalsurveys',
            name='status',
            field=models.CharField(blank=True, choices=[('IN_PROGRESS', 'En proceso'), ('CANCELED', 'Cancelada'), ('FINISHED', 'Finalizada')], default='IN_PROGRESS', null=True, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='surveys',
            name='status',
            field=models.CharField(blank=True, choices=[('IN_PROGRESS', 'En proceso'), ('CANCELED', 'Cancelada'), ('FINISHED', 'Finalizada')], default='IN_PROGRESS', null=True, verbose_name='Tipo'),
        ),
    ]
