# Generated by Django 5.0.9 on 2024-12-31 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0006_remove_historicalsurveys_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsurveys',
            name='status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pendiente'), ('IN_PROGRESS', 'En proceso'), ('CANCELED', 'Cancelada'), ('FINISHED', 'Finalizada')], default='PENDING', null=True, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='surveys',
            name='status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pendiente'), ('IN_PROGRESS', 'En proceso'), ('CANCELED', 'Cancelada'), ('FINISHED', 'Finalizada')], default='PENDING', null=True, verbose_name='Tipo'),
        ),
    ]
