# Generated by Django 5.0.9 on 2025-01-04 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0007_alter_historicalsurveys_status_alter_surveys_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsurveys',
            name='date_status_to_cancelled',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de cancelacion'),
        ),
        migrations.AddField(
            model_name='historicalsurveys',
            name='date_status_to_finalized',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de finalizado'),
        ),
        migrations.AddField(
            model_name='historicalsurveys',
            name='route',
            field=models.CharField(blank=True, null=True, verbose_name='Ruta'),
        ),
        migrations.AddField(
            model_name='surveys',
            name='date_status_to_cancelled',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de cancelacion'),
        ),
        migrations.AddField(
            model_name='surveys',
            name='date_status_to_finalized',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de finalizado'),
        ),
        migrations.AddField(
            model_name='surveys',
            name='route',
            field=models.CharField(blank=True, null=True, verbose_name='Ruta'),
        ),
    ]
