# Generated by Django 5.0.9 on 2025-01-07 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0008_historicalsurveys_date_status_to_cancelled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsurveys',
            name='folio',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Folio'),
        ),
        migrations.AddField(
            model_name='surveys',
            name='folio',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Folio'),
        ),
    ]
