# Generated by Django 5.0.9 on 2025-02-13 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0009_historicalsurveys_folio_surveys_folio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsurveys',
            name='type_3',
            field=models.CharField(blank=True, choices=[('DELIVERY_MAN', 'Repartidor'), ('CALL_CENTER', 'Call center'), ('BOTH', 'Ambos'), ('WHITE_CREAM', 'Nata Blanca'), ('BAD_TASTE', 'Mal Sabor'), ('BAD_SMELL', 'Mal Olor'), ('GREEN_WATER', 'Agua verde'), ('EXPIRED_EXPIRATION_DATE', 'Caducidad Vencida'), ('FOREIGN_BODY', 'Cuerpo extraño'), ('WARRANTY_SEAL', 'Sello de garantía'), ('BROKEN_CARAFE_WATER_LEAK', 'Garrafón roto / Fuga de agua'), ('BLUE_BLACK_PARTICLES', 'Partículas azules /negras'), ('OTHERS', 'Otros')], null=True, verbose_name='Tipo 3'),
        ),
        migrations.AlterField(
            model_name='surveys',
            name='type_3',
            field=models.CharField(blank=True, choices=[('DELIVERY_MAN', 'Repartidor'), ('CALL_CENTER', 'Call center'), ('BOTH', 'Ambos'), ('WHITE_CREAM', 'Nata Blanca'), ('BAD_TASTE', 'Mal Sabor'), ('BAD_SMELL', 'Mal Olor'), ('GREEN_WATER', 'Agua verde'), ('EXPIRED_EXPIRATION_DATE', 'Caducidad Vencida'), ('FOREIGN_BODY', 'Cuerpo extraño'), ('WARRANTY_SEAL', 'Sello de garantía'), ('BROKEN_CARAFE_WATER_LEAK', 'Garrafón roto / Fuga de agua'), ('BLUE_BLACK_PARTICLES', 'Partículas azules /negras'), ('OTHERS', 'Otros')], null=True, verbose_name='Tipo 3'),
        ),
    ]
